CREATE TABLE audit_programmes (
    id CHAR(36) NOT NULL,
    tenant_id CHAR(36) NOT NULL,
    programme_number VARCHAR(32) NOT NULL,
    client_id CHAR(36) NOT NULL,
    scheme_id CHAR(36) NOT NULL,
    standard_id CHAR(36) NULL,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    cycle_start_on DATE NULL,
    cycle_end_on DATE NULL,
    notes TEXT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by VARCHAR(64) NOT NULL,
    updated_by VARCHAR(64) NOT NULL,
    deleted_at DATETIME(6) NULL,
    version INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_programmes_tenant_number (tenant_id, programme_number),
    KEY idx_programmes_tenant_client (tenant_id, client_id),
    KEY idx_programmes_tenant_status (tenant_id, status),
    CONSTRAINT fk_programmes_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_programmes_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT fk_programmes_scheme FOREIGN KEY (scheme_id) REFERENCES schemes (id),
    CONSTRAINT fk_programmes_standard FOREIGN KEY (standard_id) REFERENCES standards (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE audits (
    id CHAR(36) NOT NULL,
    tenant_id CHAR(36) NOT NULL,
    audit_number VARCHAR(32) NOT NULL,
    programme_id CHAR(36) NOT NULL,
    client_id CHAR(36) NOT NULL,
    scheme_id CHAR(36) NOT NULL,
    standard_id CHAR(36) NULL,
    checklist_id CHAR(36) NULL,
    name VARCHAR(255) NOT NULL,
    audit_type VARCHAR(32) NOT NULL,
    stage VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    planned_start_on DATE NULL,
    planned_end_on DATE NULL,
    notes TEXT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by VARCHAR(64) NOT NULL,
    updated_by VARCHAR(64) NOT NULL,
    deleted_at DATETIME(6) NULL,
    version INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_audits_tenant_number (tenant_id, audit_number),
    KEY idx_audits_tenant_client_status (tenant_id, client_id, status),
    KEY idx_audits_programme (programme_id),
    CONSTRAINT fk_audits_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_audits_programme FOREIGN KEY (programme_id) REFERENCES audit_programmes (id),
    CONSTRAINT fk_audits_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT fk_audits_scheme FOREIGN KEY (scheme_id) REFERENCES schemes (id),
    CONSTRAINT fk_audits_standard FOREIGN KEY (standard_id) REFERENCES standards (id),
    CONSTRAINT fk_audits_checklist FOREIGN KEY (checklist_id) REFERENCES checklists (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE audit_sites (
    id CHAR(36) NOT NULL,
    tenant_id CHAR(36) NOT NULL,
    audit_id CHAR(36) NOT NULL,
    site_id CHAR(36) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by VARCHAR(64) NOT NULL,
    updated_by VARCHAR(64) NOT NULL,
    deleted_at DATETIME(6) NULL,
    version INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_audit_sites (audit_id, site_id),
    KEY idx_audit_sites_tenant (tenant_id, audit_id),
    CONSTRAINT fk_audit_sites_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_audit_sites_audit FOREIGN KEY (audit_id) REFERENCES audits (id),
    CONSTRAINT fk_audit_sites_site FOREIGN KEY (site_id) REFERENCES sites (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE audit_assignments (
    id CHAR(36) NOT NULL,
    tenant_id CHAR(36) NOT NULL,
    audit_id CHAR(36) NOT NULL,
    auditor_id CHAR(36) NOT NULL,
    assignment_role VARCHAR(32) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by VARCHAR(64) NOT NULL,
    updated_by VARCHAR(64) NOT NULL,
    deleted_at DATETIME(6) NULL,
    version INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_audit_assignments (audit_id, auditor_id),
    KEY idx_audit_assignments_tenant (tenant_id, audit_id),
    CONSTRAINT fk_audit_assignments_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_audit_assignments_audit FOREIGN KEY (audit_id) REFERENCES audits (id),
    CONSTRAINT fk_audit_assignments_auditor FOREIGN KEY (auditor_id) REFERENCES auditors (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
