CREATE TABLE findings (
    id CHAR(36) NOT NULL,
    tenant_id CHAR(36) NOT NULL,
    finding_number VARCHAR(32) NOT NULL,
    audit_id CHAR(36) NOT NULL,
    client_id CHAR(36) NOT NULL,
    site_id CHAR(36) NULL,
    response_id CHAR(36) NULL,
    clause_id CHAR(36) NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    severity VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    closed_on DATE NULL,
    notes TEXT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by VARCHAR(64) NOT NULL,
    updated_by VARCHAR(64) NOT NULL,
    deleted_at DATETIME(6) NULL,
    version INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_findings_tenant_number (tenant_id, finding_number),
    KEY idx_findings_tenant_client_status (tenant_id, client_id, status),
    KEY idx_findings_audit (audit_id),
    CONSTRAINT fk_findings_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_findings_audit FOREIGN KEY (audit_id) REFERENCES audits (id),
    CONSTRAINT fk_findings_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT fk_findings_site FOREIGN KEY (site_id) REFERENCES sites (id),
    CONSTRAINT fk_findings_response FOREIGN KEY (response_id) REFERENCES audit_checklist_responses (id),
    CONSTRAINT fk_findings_clause FOREIGN KEY (clause_id) REFERENCES standard_clauses (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE capa_actions (
    id CHAR(36) NOT NULL,
    tenant_id CHAR(36) NOT NULL,
    capa_number VARCHAR(32) NOT NULL,
    finding_id CHAR(36) NOT NULL,
    description TEXT NOT NULL,
    due_on DATE NOT NULL,
    completed_on DATE NULL,
    status VARCHAR(32) NOT NULL,
    notes TEXT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by VARCHAR(64) NOT NULL,
    updated_by VARCHAR(64) NOT NULL,
    deleted_at DATETIME(6) NULL,
    version INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_capa_tenant_number (tenant_id, capa_number),
    KEY idx_capa_finding (finding_id),
    KEY idx_capa_tenant_status_due (tenant_id, status, due_on),
    CONSTRAINT fk_capa_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_capa_finding FOREIGN KEY (finding_id) REFERENCES findings (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
